"""empty message

Revision ID: 29999e556a9a
Revises: None
Create Date: 2016-04-01 09:43:11.377387

"""

# revision identifiers, used by Alembic.
revision = '29999e556a9a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('posts')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=20), nullable=False),
    sa.Column('description', sa.VARCHAR(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('email', sa.CHAR(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
